// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nujlxrdrdqfwhgsjiwlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51amx4cmRyZHFmd2hnc2ppd2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDA5NjMsImV4cCI6MjA3MzUxNjk2M30.OMuxrFvrvdRxjoNevRsyh97RpwdqJn-2Ui-arkOppMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});